apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-credentials
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "aws-secret-arn"
          objectVersion: "aws-secret-versionid"
          jmesPath: 
          - path: DATABASE_USER
            objectAlias: dbuser
          - path: DATABASE_PASSWORD
            objectAlias: dbpassword

---