apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dbcredentials
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-2:431877974142:secret:dbcredentials-uWE5Ed"
          objectVersion: "44493d5a-db4a-4cc2-b2f4-8960d527783c"
          jmesPath: 
          - path: DATABASE_USER
            objectAlias: dbuser
          - path: DATABASE_PASSWORD
            objectAlias: dbpassword

---