apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dbcredentialss
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-2:431877974142:secret:dbcredentialss-3Mzlvg"
          objectVersion: "5dc19e7f-0c6d-4a95-b025-fe31afdf5b57"
          jmesPath: 
          - path: DATABASE_USER
            objectAlias: dbuser
          - path: DATABASE_PASSWORD
            objectAlias: dbpassword

---