apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brokencrystalss
  region: us-east-2

iam:
  withOIDC: true

nodeGroups:
  - name: ng-general
    instanceType: t3.medium
    instanceName: brokencrystals-node
    desiredCapacity: 1