name: Cloudsec-test

on:
   workflow_dispatch:
   
permissions:
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SAST Scan
        run: grep -r -e "password" -e "secret" -e "keys" .
      
     # - name: Debug Docker Username
     #   run: echo "Docker Hub username: ${{ secrets.DOCKERHUB_USERNAME }}"

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker images
        run: docker-compose --file=docker-compose.local.yml up -d --build

      - name: Checking for images built and pulled 
        run: sudo docker images

      # Tagging the Docker images manually using docker tag command
      - name: Tag Docker images
        run: |
          docker tag brokencrystals-nodejs:latest ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:latest
          docker tag brokencrystals-nodejs:latest ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:v1.0
          docker tag postgres:latest ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker tag postgres:latest ${{ secrets.DOCKERHUB_USERNAME }}/postgres:v1.0
          docker tag sj26/mailcatcher:latest ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:latest
          docker tag sj26/mailcatcher:latest ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:v1.0
      
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:v1.0

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.CSN_TOKEN }}
           publish_dir: .

  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: OWASP ZAP DAST Scan
        continue-on-error: true
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t 'https://seyramgabriel.github.io/brokencrystals/' || true
