name: Cloudsec-test

on:
   #push:
     #branches:
       #- stable
       
   workflow_dispatch:
   
permissions:
  checks: write
  #contents: read
  #id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SAST Scan
        run: grep -r -e "password" -e "secret" -e "keys" .
        # run: grep -Ri -w '(password|passwd|pass|secret|keys)' .
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
              docker-compose --file=docker-compose.local.yml -d --build
              

      - name: Tag Docker image for app
        uses: actions/docker/tag-action@v1
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:latest,${{ secrets.DOCKER_USERNAME }}/brokencrystals-nodejs:v1.0

      
      - name: Tag Docker image for db
        uses: actions/docker/tag-action@v1
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest,${{ secrets.DOCKERHUB_USERNAME }}/postgres:v1.0

      
      - name: Tag Docker image for proxy
        uses: actions/docker/tag-action@v1
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:latest,${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:v1.0

      
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/brokencrystals-nodejs:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sj26/mailcatcher:v1.0

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.CSN_TOKEN }}
           publish_dir: .
   #   - name: GitHub Pages
   #     uses: github/pages@v2
   #     with:
   #       github_token: ${{ secrets.CSN_TOKEN }}
   #       path: /docs  # Specify the folder containing your index.html file
   
  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: OWASP ZAP DAST Scan
        continue-on-error: true
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t 'https://seyramgabriel.github.io/brokencrystals/' || true
